import { PDFDocument, degrees } from 'pdf-lib'
import JSZip from 'jszip'

export async function loadPdf(bytes:Uint8Array){return PDFDocument.load(bytes)}
export async function mergePdfs(files:File[]){const out=await PDFDocument.create();for(const file of files){const src=await PDFDocument.load(await file.arrayBuffer());const pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p))}return out.save()}
export async function selectPdfPages(file:File,pageNumbers:number[]){const src=await PDFDocument.load(await file.arrayBuffer());const out=await PDFDocument.create();const valid=pageNumbers.filter(n=>Number.isInteger(n)&&n>=1&&n<=src.getPageCount()).map(n=>n-1);const pages=await out.copyPages(src,valid);pages.forEach(p=>out.addPage(p));return out.save()}
export async function deletePdfPages(file:File,pageNumbers:number[]){const src=await PDFDocument.load(await file.arrayBuffer());const remove=new Set(pageNumbers.map(n=>n-1));const out=await PDFDocument.create();const keep=src.getPageIndices().filter(i=>!remove.has(i));const pages=await out.copyPages(src,keep);pages.forEach(p=>out.addPage(p));return out.save()}
export async function reorderPdfPages(file:File,order:number[]){const src=await PDFDocument.load(await file.arrayBuffer());if(order.length!==src.getPageCount())throw new Error(`Provide exactly ${src.getPageCount()} page numbers.`);const out=await PDFDocument.create();const pages=await out.copyPages(src,order.map(n=>n-1));pages.forEach(p=>out.addPage(p));return out.save()}
export async function rotatePdf(file:File,angle:90|180|270){const doc=await PDFDocument.load(await file.arrayBuffer());doc.getPages().forEach(p=>p.setRotation(degrees((p.getRotation().angle+angle)%360)));return doc.save()}
async function pdfJs(){const mod=await import('pdfjs-dist');return mod}
export async function renderPdfToJpg(file:File,quality=.82){const pdfjs=await pdfJs();const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;const zip= new JSZip();for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const viewport=page.getViewport({scale:1.5});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas is unavailable.');await page.render({canvas,canvasContext:ctx,viewport}).promise;const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/jpeg',quality));if(blob)zip.file(`page-${i}.jpg`,blob)}return zip.generateAsync({type:'blob'})}
export async function imagesToPdf(files:File[]){const out=await PDFDocument.create();for(const file of files){const bytes=new Uint8Array(await file.arrayBuffer());const type=file.type;let image;if(type==='image/png')image=await out.embedPng(bytes);else image=await out.embedJpg(bytes);const page=out.addPage([image.width,image.height]);page.drawImage(image,{x:0,y:0,width:image.width,height:image.height})}return out.save()}
export async function compressPdf(file:File,quality=.72,scale=1.25){const pdfjs=await pdfJs();const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;const out=await PDFDocument.create();for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const viewport=page.getViewport({scale});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas is unavailable.');await page.render({canvas,canvasContext:ctx,viewport}).promise;const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/jpeg',quality));if(!blob)throw new Error('Could not rasterize PDF page.');const image=await out.embedJpg(new Uint8Array(await blob.arrayBuffer()));const p=out.addPage([image.width,image.height]);p.drawImage(image,{x:0,y:0,width:image.width,height:image.height})}return out.save()}
